### ISSUE TITLE
feature

### ISSUE THREAD

**Issue by ghost** [Mo0ns/Roblox-Whitelist#3]
can u make it that we can check if the user bot a product on roblox? and if so give them a role

**Comment by PixeIPenguin** [comment]
So sorry for the late response! I do not get notifications for issues and I haven't been active on github much...

Let's get started! 

So the first thing we want is a API (which is down below).

https://inventory.roblox.com/v1/users/109176680/items/GamePass//202385

So obviously you need to replace the "109176680" with the actual user ID.

Your next question may be, how do I get their user id?
There are a few answers to that!
1: Get it from their command they run.
2: Get their user id off of join but search for their user ID using famous roblox verification bot's APIs.

Now replace "202385" with your game pass.

Once you have done this, you are able to make a GET request to the link and see if the "data" array is null or not.
If the "data" array has nothing in it, they do not own it. However, if it has the type, ID, name, and instanceId they own the game pass.

Hopefully this helps, good luck!

**Comment by w0lvv** [comment]
ok where do we put it?

**Comment by PixeIPenguin** [comment]
> ok where do we put it?

Put it in the discord bot files however you control your commands.
